AddAssembleRecipe("bread","/","bread")
AddAssembleRecipe("cooked_chopped_steak","bread")
AddAssembleRecipe("cooked_chopped_steak","bread,cooked_chopped_steak")
AddAssembleRecipe("cooked_chopped_steak","bread,cooked_chopped_steak,cooked_chopped_steak")
AddAssembleRecipe("lettuce_leaf","bread,cooked_chopped_steak,cooked_chopped_steak,cooked_chopped_steak")
AddAssembleRecipe("lettuce_leaf","bread,cooked_chopped_steak,cooked_chopped_steak,cooked_chopped_steak,lettuce_leaf")
AddAssembleRecipe("lettuce_leaf","bread,cooked_chopped_steak,cooked_chopped_steak,cooked_chopped_steak,lettuce_leaf,lettuce_leaf")
AddAssembleRecipe("tomato","bread,cooked_chopped_steak,cooked_chopped_steak,cooked_chopped_steak,lettuce_leaf,lettuce_leaf,lettuce_leaf")
AddAssembleRecipe("fries","bread,cooked_chopped_steak,cooked_chopped_steak,cooked_chopped_steak,lettuce_leaf,lettuce_leaf,lettuce_leaf","american", {isFinished = true})