# This is a basic workflow to upload files 
# from GitHub to server via GitHub Actions
name: Push on DEV Server

# Controls when the workflow will run
on:

  # Triggers the workflow on push request event 
  # but only for the specific branch
  push:
    branches: [ dev ]

# A workflow run is made up of one or more jobs 
# that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "SFTP-Deploy-Action"
  SFTP-Deploy-Action-DEV:
    name: SFTP-Deploy-Action-DEV

    # The type of runner that the job will run on 
    # (depends on server but usually this value is works)
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks 
    # that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, 
      # so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
        with:

          # Fetch all history for all tags and branches
          fetch-depth: 0

          # Checkout a specific branch
          ref: dev
      # This is a composite GitHub Action (Linux runner) 
      # for deploying repository content to remote server
      - name: SFTP-Deploy-Action
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: sftp

          # Credentials for SFTP access to server using GitHub secrets
          remote-host: ${{ secrets.SFTP_HOST }}
          remote-user: ${{ secrets.SFTP_USER }}
          remote-password: ${{ secrets.SFTP_PASSWORD }}

          # Path for specific folder on server for files deployment
          remote-path: /garrysmod/gamemodes/projectvisualis/plugins/good_foods

          # Port for SFTP access to server
          remote-port: 2225
